groups:
    - name: Availability
      rules:
  # This rule can be very noisy in dynamic infra with legitimate container start/stop/deployment.
      - alert: ContainerKilled
        expr: time() - container_last_seen > 30
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: Container killed (instance {{ $labels.instance }})
          description: "A container has disappeared\n Container name = {{ $labels.name }}"

      - alert: MySQLDown
        annotations:
          description: "MySQL {{$labels.job}} on {{$labels.instance}} is not up."
          summary: MySQL not up
        expr: mysql_up != 1
        for: 15s
        labels:
          severity: critical

